fotoblog/urls.py
from multiprocessing import context
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.contrib.auth.views import LoginView

import authentication.views
import blog.views

urlpatterns = [
    path("admin/", admin.site.urls),
    # path('', authentication.views.LoginPage.as_view(), name='login'),
    path('', LoginView.as_view(
        template_name="authentication/login.html",
        redirect_authenticated_user=True), name="login" ),
    path('logout/', authentication.views.logout_user, name='logout'),
    path('home/', blog.views.home, name='home'),
    path('signup', authentication.views.signup_page, name="signup"),
    path('photo/upload', blog.views.photo_upload, name='photo_upload'),
    path('blog/create', blog.views.blog_and_photo_upload, name='blog_create'),
    path('blog/<int:blog_id>', blog.views.view_blog, name='view_blog'),
    path('blog/<int:blog_id>/edit', blog.views.edit_blog, name='edit_blog'),
    path('photo/upload-multiple/', blog.views.create_multiple_photos,name='create_multiple_photos'),
    path('follow-users/', blog.views.follow_users, name='follow_users'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from email.mime import image
from tkinter import CASCADE
from django.db import models
from django.conf import settings    

from PIL import Image


class Photo(models.Model):
    image = models.ImageField()
    caption = models.CharField(max_length=128, blank=True)
    uploader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)

    IMAGE_MAX_SIZE = (800, 800)

    def resize_image(self):
        image = Image.open(self.image)
        image.thumbnail(self.IMAGE_MAX_SIZE)
        image.save(self.image.path)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.resize_image()

class Blog(models.Model):
    photo = models.ForeignKey(Photo, null=True, on_delete=models.SET_NULL, blank=True)
    title = models.CharField(max_length=128)
    content = models.CharField(max_length=5000)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    starred = models.BooleanField(default=False)
    contributors = models.ManyToManyField(settings.AUTH_USER_MODEL, through='BlogContributor', related_name='contributions')

class BlogContributor(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    contributor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contributions = models.CharField(max_length=255, blank=True)

    class Meta:
        unique_together = ('blog', 'contributor')

templates/base.html
<html>
    <head>
        <title>FotoBlog</title>
    </head>
    <body>
        <h1>FotoBlog</h1>
        <p><a href="{% url 'home' %}">Accueil</a></p>
        <p><a href="{% url 'blog_create' %}">Écrire un billet</a></p>
        {% if perms.blog.add_photo %}
        <p><a href="{% url 'photo_upload' %}">Télécharger une photo</a></p>
        {% endif %}
        <p><a href="{% url 'follow_users' %}">Suivre des utilisateurs</a></p>
        <p><a href="{% url 'create_multiple_photos' %}">Télécharger plusieurs photos</a></p>
        {% block content %}{% endblock content %}
        {% if user.is_authenticated %}
            <p>Vous êtes connecté en tant que {{ request.user }}. <a href="{% url 'logout' %}">Se déconnecter</a></p>
        {% endif %}
    </body>
</html>